name: Deploy docs to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Allow this job to deploy to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment; don't cancel in-progress production deploys.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4- name: Install, build, and upload site
        uses: withastro/action@56781b97402ce0487b7e61ce2cb960c0e2cc5289  # v3with:
          # Build defaults to `pnpm` because a pnpm-lock.yaml is present.
          node-version: 22

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # v4